name: split-bill

services:
  app:
    image: stevenrhenaldy/split-bill-app
    build: ../backend
    ports:
      - 3000:3000
    networks:
      - split-bill-network
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TABLE=${DB_TABLE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_LIFETIME=${JWT_LIFETIME}
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - split-bill-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_TABLE}
    volumes:
      - ./data/db/:/var/lib/postgresql/data
    networks:
      - split-bill-network
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U split-bill -d split-bill'"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  split-bill-network: